### ISSUE TITLE
Include Game Icons web font

### ISSUE THREAD

**Issue by guumaster** [effortlessmountain/ironsworn-asset-workbench#25]
There is an npm package called [@rolodromo/gameicons-webfont](https://www.npmjs.com/package/@rolodromo/gameicons-webfont) that could be a nice feature to include here. 

Basically is a web font that you can include and use all available icons in [Game-icons.net](https://game-icons.net/).

You can include it in your site just by adding this:
```
<head>
  <link href="https://unpkg.com/@rolodromo/gameicons-webfont/css/rpgen-gameicons.min.css" rel="stylesheet" />
</head>
```
And then use it by keyword in your HTML, ex: `<i class="gi gi-swordwoman"></i>`.

Here is screenshot of how some icons:
![image](https://user-images.githubusercontent.com/765396/99885526-d8f8b980-2c35-11eb-84f6-172100b4e030.png)

**Comment by effortlessmountain** [comment]
Thanks for the info! I won't be doing anything with it in the meantime due to the following:
 * the webfont being megabytes in size
 * Game-Icons.Net has a better search than is possible just by name
 * For anyone publishing the assets made here, it lacks proper attribution information on the icons
