### ISSUE TITLE
Malformed icon when downloading card in Chrome

### ISSUE THREAD

**Issue by SHiLLySiT** [effortlessmountain/ironsworn-asset-workbench#5]
After clicking the download button and being brought to the download page, the card icon appears malformed.

![Screenshot_304](https://user-images.githubusercontent.com/950984/76673967-ae634680-6567-11ea-8562-b36ade38caa4.png)

I'm on Chrome 80.0.3987.132. Firefox appears to be working as intended.

**Comment by effortlessmountain** [comment]
Thanks for reporting! I've been able to replicate this as well on Chrome, and also have it working in Firefox. Fixing this is on the list :+1:
